name: Publish

on: 
    push: 
        branches: [main]

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions: 
            contents: read
            packages: write

        strategy:
            matrix:
                node-version: ["18.x"]
        
        steps:
            - uses: actions/checkout@v4
            - name: Set up Node
              uses: actions/setup-node@v3
              with: 
                node-version: ${{matrix.node-version}}
            - run: npm ci
            - run: npm build
            - run: |
                echo @Favour-Aransiola:https://npm.pkg.github.com/ > build/.npmrc
                echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> build/.npmrc
            - run: npm publish
              working-directory: ./build
              env:
                NPM_TOKEN: ${{secrets.GITHUB_TOKEN}}
                

              